twitch:
  api:
    url: https://api.twitch.tv/

spring:
  application:
    name: twitch-auth-gateway
  cloud:
    gateway:
      routes:
        - id: twitch
          uri: ${twitch.api.url}
          predicates:
            - name: Path
              args:
                - /helix/{*segment}
          filters:
            - name: TwitchAuthorization

server:
  port: 80

management:
  endpoints:
    web:
      exposure:
        include: health,prometheus
---
spring:
  config:
    activate:
      on-cloud-platform: kubernetes
  main:
    banner-mode: off

logging:
  config: classpath:logback-kubernetes.xml
