twitch:
  api:
    url: https://api.twitch.tv/

spring:
  application:
    name: twitch-auth-gateway
  cloud:
    gateway:
      routes:
        - id: twitch
          uri: ${twitch.api.url}
          predicates:
            - name: Path
              args:
                - /helix/*
          filters:
            - name: TwitchAuthorization

server:
  port: 80

management:
  endpoints:
    web:
      exposure:
        include: health,prometheus
